name: Mirror to ExpenseTrackerApp-BackEnd Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout service repo
        uses: actions/checkout@v2

      - name: Push to aggregator repo
        env:
          PAT: ${{ secrets.ActionsToken_PAT }}
        run: |
          # Configure Git identity (use your own name/email so commits show as you)
          git config --global user.name "Harshit-Anandd"
          git config --global user.email "harshit.anandd@gmail.com"

          # Add aggregator remote
          git remote add aggregator https://Harshit-Anandd:${PAT}@github.com/Harshit-Anandd/ExpenseTrackerApp-BackEnd.git
          git fetch aggregator

          # Push the entire commit history to aggregator branch
          git push aggregator main:auth-service --force
